language: php

php:
  - "7.1"

env:
  - WP_VERSION=4.9

cache:
  directories:
    - $HOME/.composer/cache

install:
    - composer install

jobs:
  include:
    - stage: inspect
      script: ./vendor/bin/phing inspect
    - stage: test
      script: ./vendor/bin/phing tests
    - stage: build
      script: ./vendor/bin/phing build
    - stage: deploy
      script: echo "Deploying to GitHub releases"
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_ACCESS_TOKEN
        file:
          - ./build/archives/ignico.zip
          - ./build/archives/ignico.tar.gz
        skip_cleanup: true
        on:
          tags: true

stages:
  - inspect
  - test
  - build
  - deploy

