language: php

php:
  - "7.1"

env:
  - WP_VERSION=4.9

cache:
  directories:
    - $HOME/.composer/cache

install:
    - composer install

jobs:
  include:
    - stage: inspect
      script: ./vendor/bin/phing inspect
    - stage: test
      script: ./vendor/bin/phing tests

stages:
  - inspect
  - test

