version: '3'
services:
  app:
    image: motivast/wp-app
    volumes:
      - ./:/var/www:cached
    working_dir: /var/www

  web:
    image: motivast/wp-web
    ports:
      - 8080:80
    volumes:
      - ./:/var/www:cached
      - ./docker/virtualhost.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www

  database:
    image: mysql:5.7
    volumes:
      - db_ignico_wordpress:/var/lib/mysql:cached
    environment:
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  db_ignico_wordpress:
