version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: ./docker/app.dev.dockerfile
        volumes:
            - ./:/var/www:cached
        working_dir: /var/www
        logging:
            driver: syslog
            options:
                tag: igwp-app
        restart: always
        networks:
            - igwp

    web:
        build:
            context: ./
            dockerfile: ./docker/web.dev.dockerfile
        volumes:
            - ./:/var/www:cached
        working_dir: /var/www
        logging:
            driver: syslog
            options:
                tag: igwp-web
        restart: always
        networks:
            - igwp

networks:
    igwp:
        external: true
